"""Rename categories to category

Revision ID: 89b0612b110d
Revises: a558e1547047
Create Date: 2023-10-31 17:47:12.731871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89b0612b110d'
down_revision = 'a558e1547047'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(length=200), nullable=False))
        batch_op.drop_column('categories')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('todo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('categories', sa.VARCHAR(length=200), nullable=False))
        batch_op.drop_column('category')

    # ### end Alembic commands ###
